DROP DATABASE IF EXISTS M2_BBDD;
CREATE DATABASE M2_BBDD;

USE M2_BBDD;

CREATE TABLE player(
PLAYERNAME VARCHAR(60) NOT NULL,
USERID VARCHAR(60),
PASSWORD_P VARCHAR(60),
TOTALPOINTS INT,
PRIMARY KEY(USERID)
)ENGINE=InnoDB;

CREATE TABLE game(
GAMEID INT NOT NULL,
GAME_DATE INT,
GAME_TIME FLOAT,
DURATION FLOAT,
WINNER VARCHAR(60),
LOSER VARCHAR(60),
PRIMARY KEY(GAMEID)
)ENGINE=InnoDB;

CREATE TABLE bridge(
IDUSER INT,
IDGAME INT,
FOREIGN KEY (IDUSER) REFERENCES player(USERID),
FOREIGN KEY (IDGAME) REFERENCES game(GAMEID)
)ENGINE=InnoDB;

INSERT INTO player VALUES (1, 'ABC', 'abc',12122);
INSERT INTO player VALUES (2, 'DEF', 'def', 34412);

INSERT INTO game VALUES (1, 11, 12, 4, 'ABC', 'DEF');
INSERT INTO game VALUES (2, 11, 12, 4, 'DEF', 'ABC');
